FichX\FichXBundle\Entity\MateriaHasUsuario:
    type: entity
    table: materia_has_usuario
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
    manyToOne:
        idMateria:
            targetEntity: Materias
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_materia:
                    referencedColumnName: id
            orphanRemoval: false
        idUsuario:
            targetEntity: Usuarios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_usuario:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
